export const iconMap: Record<string, string> = {
  // === FILES by exact name ===
  "package.json": "file_type_npm.svg",
  "package-lock.json": "file_type_npm.svg",
  "readme.md": "file_type_markdown.svg",
  "vite.config.js": "file_type_vite.svg",
  "vite.config.ts": "file_type_vite.svg",
  "tsconfig.json": "file_type_tsconfig.svg",
  "tsconfig.node.json": "file_type_tsconfig.svg",
  "eslint.config.js": "file_type_eslint.svg",
  "eslint.config.ts": "file_type_eslint.svg",
  ".gitignore": "file_type_git.svg",
  "index.html": "file_type_html.svg",
  "tailwind.config.js": "file_type_tailwind.svg",
  "postcss.config.js": "file_type_postcss.svg",
  "Dockerfile": "file_type_docker.svg",
  "Makefile": "file_type_makefile.svg",
  "vite-env.d.ts": "file_type_d_ts.svg", 
  // === FILES by extension ===
  js: "file_type_js.svg",
  jsx: "file_type_react.svg",
  ts: "file_type_typescript.svg",
  tsx: "file_type_reactts.svg",
  json: "file_type_json.svg",
  html: "file_type_html.svg",
  css: "file_type_css.svg",
  scss: "file_type_scss.svg",
  md: "file_type_markdown.svg",
  svg: "file_type_svg.svg",
  png: "file_type_image.svg",
  jpg: "file_type_image.svg",
  jpeg: "file_type_image.svg",
  gif: "file_type_image.svg",
  env: "file_type_env.svg",
  sh: "file_type_shell.svg",
  yml: "file_type_yaml.svg",
  yaml: "file_type_yaml.svg",
  lock: "file_type_lock.svg",
  d_ts: "file_type_d_ts.svg",
  map: "file_type_map.svg",

  // === COMMON REACT FILES ===
  "App.tsx": "file_type_reactts.svg",
  "App.jsx": "file_type_react.svg",
  "main.tsx": "file_type_reactts.svg",
  "index.tsx": "file_type_reactts.svg",
  "index.js": "file_type_js.svg",
  "setupTests.ts": "file_type_testts.svg",
  "App.css": "file_type_css.svg",
  "index.css": "file_type_css.svg",

  // === TESTS ===
  "App.test.tsx": "file_type_testts.svg",
  "App.test.jsx": "file_type_testjs.svg",

  // === FOLDERS ===
  src_folder: "folder_type_src.svg",
  public_folder: "folder_type_public.svg",
  assets_folder: "folder_type_asset.svg",
  components_folder: "folder_type_component.svg",
  hooks_folder: "folder_type_hooks.svg",
  context_folder: "folder_type_context.svg",
  utils_folder: "folder_type_utils.svg",
  styles_folder: "folder_type_styles.svg",
  tests_folder: "folder_type_test.svg",
  node_modules_folder: "folder_type_node.svg",

  // === OTHER SPECIAL FOLDERS ===
  ".vscode_folder": "folder_type_vscode.svg",
  ".git_folder": "folder_type_git.svg",
  "build_folder": "folder_type_build.svg",
  "dist_folder": "folder_type_dist.svg",
};
