export const iconMap: Record<string, string> = {
  // === FILES by exact name ===
  "package.json": "file_type_npm",
  "package-lock.json": "file_type_npm",
  "readme.md": "file_type_markdown",
  "vite.config.js": "file_type_vite",
  "vite.config.ts": "file_type_vite",
  "tsconfig.json": "file_type_tsconfig",
  "tsconfig.node.json": "file_type_tsconfig",
  "eslint.config.js": "file_type_eslint",
  "eslint.config.ts": "file_type_eslint",
  ".gitignore": "file_type_git",
  "index.html": "file_type_html",
  "tailwind.config.js": "file_type_tailwind",
  "postcss.config.js": "file_type_postcss",
  "Dockerfile": "file_type_docker",
  "Makefile": "file_type_makefile",
  "vite-env.d.ts": "file_type_typescript", 
  // === FILES by extension ===
  js: "file_type_js",
  jsx: "file_type_react",
  ts: "file_type_typescript",
  tsx: "file_type_reactts",
  json: "file_type_json",
  html: "file_type_html",
  css: "file_type_css",
  scss: "file_type_scss",
  md: "file_type_markdown",
  svg: "file_type_svg",
  png: "file_type_image",
  jpg: "file_type_image",
  jpeg: "file_type_image",
  gif: "file_type_image",
  env: "file_type_env",
  sh: "file_type_shell",
  yml: "file_type_yaml",
  yaml: "file_type_yaml",
  lock: "file_type_lock",
  d_ts: "file_type_d_ts",
  map: "file_type_map",

  // === COMMON REACT FILES ===
  "App.tsx": "file_type_reactts",
  "App.jsx": "file_type_react",
  "main.tsx": "file_type_reactts",
  "index.tsx": "file_type_reactts",
  "index.js": "file_type_js",
  "setupTests.ts": "file_type_testts",
  "App.css": "file_type_css",
  "index.css": "file_type_css",

  // === TESTS ===
  "App.test.tsx": "file_type_testts",
  "App.test.jsx": "file_type_testjs",

  // === FOLDERS ===
  src_folder: "folder_type_src",
  public_folder: "folder_type_public",
  assets_folder: "folder_type_asset",
  components_folder: "folder_type_component",
  hooks_folder: "folder_type_hooks",
  context_folder: "folder_type_context",
  utils_folder: "folder_type_utils",
  styles_folder: "folder_type_styles",
  tests_folder: "folder_type_test",
  node_modules_folder: "folder_type_node",

  // === OTHER SPECIAL FOLDERS ===
  ".vscode_folder": "folder_type_vscode",
  ".git_folder": "folder_type_git",
  "build_folder": "folder_type_build",
  "dist_folder": "folder_type_dist",
};
